server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/p2p_cheat?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 521piiig

redis:
  host: 127.0.0.1
  port: 6379
  database: 0
  timeout: 2000ms
  lettuce:
    pool:
      # 连接池最大连接数
      max-active: 20
      # 连接池中的最小空闲连接
      max-idle: 10
      # 连接池最大阻塞等待时间(使用负数表示没有限制,单位ms)
      max-wait: 3000

oauth2:
  github:
    clientId: f1bfd0558a7922de98d2
    clientSecret: d03893ab22909c7cfa7f188532e5dbb314f6d2b8
    authorizeUrl: https://github.com/login/oauth/authorize
    redirectUrl : http://localhost:8081/auth/callback
    accessTokenUrl: https://github.com/login/oauth/access_token
    userInfoUrl: https://api.github.com/user

